# Generated by Django 5.0.3 on 2024-03-13 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthorDjango",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=10000, unique=True)),
                ("born_date", models.CharField(max_length=10000)),
                ("born_location", models.CharField(max_length=50000)),
                ("description", models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="QuoteDjango",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.JSONField()),
                ("quote", models.CharField(max_length=10000)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.authordjango",
                    ),
                ),
            ],
        ),
    ]
